feat: enabled invite_accepter
DNXLabs/terraform-aws-guardduty pull request #7
Opened 2023-02-21 18:49 UTC by rsmets

Allow for use of this module within AWS Organizations that already have guard duty enabled and are under management from a Security Hub admin account. 

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the CONTRIBUTING.md doc.
- [x] I have added necessary documentation (if appropriate).
- [x] Any dependent changes have been merged and published in downstream modules.

## Further comments

Without the ability to disable the invite acceptor or the initial enablement of the detector itself then this module could never be used within an AWS setup that already has the Guard Duty enabled at the Organization level. 

The variables I introduced are none-breaking, in the sense that anyone using the module will not have to update definitions as the default is the same as the previous module version.

All the changes I have tested in my own AWS env which contains the situation I was solving for.

2023-04-08 00:39 UTC, rsmets commented
@soareseds @arthurbdiniz @adenot @caiovfernandes This PR has sat for a month and a half. Mind taking a look and merging?

2023-08-09 16:42 UTC, rsmets commented
@soareseds @arthurbdiniz @adenot @caiovfernandes poke.

2023-08-12 12:42 UTC, caiovfernandes requested changes
@rsmets A few changes are required to accept your PR.
Can you please solve those?
I'll keep looking at this PR and reply to you as soon as I can.

Thanks for your contribution.

2023-08-12 12:42 UTC, caiovfernandes commented on _variables.tf
> +variable "enable_detector" {
@rsmets Please add the variables types

2023-08-12 12:42 UTC, caiovfernandes commented on _variables.tf
> +variable "create_invite_accepter" {
@rsmets Please add variable type

2023-08-12 12:42 UTC, caiovfernandes commented on _variables.tf
> +variable "member_detector_id" {
@rsmets Please add variable type

2023-08-17 22:50 UTC, rsmets commented
@caiovfernandes I did you one better - I added types to all the variables (they were not defined sans one, which is why I left them off originally).

2023-08-17 23:01 UTC, caiovfernandes approved these changes

2023-08-17 23:01 UTC, merged